### ISSUE TITLE
aiopg closes event loop on failed connection

### ISSUE THREAD

**Issue by te-je** [aio-libs/aiopg#111]
When a connection to postgres fails, the asyncio event loop is closed. This prevents me from running any further coroutines (in particular, even those unrelated to aiopg) after a connection fails, which isn't always desirable.

**Comment by bitdancer** [comment]
I've not experienced this problem.  What specifically do you mean by "fails", and can you provide a simple reproducer?

**Comment by te-je** [comment]
Sorry, I did meant to do that, but I was running on fumes when I submitted this.

Further investigation shows that this behavior only reproduces when trying to connect to postgres on `localhost`.

Here's the code to reproduce the behavior:

```python
import asyncio
from aiopg.sa import create_engine

async def postgres_stuff():
    # If I specify a host, other than 'localhost' below, the
    # thing works as expected. i.e., omitting the host argument or
    # giving 'localhost' reproduces this behavior.
    async with create_engine(database="foo") as engine:
        async with engine.acquire() as conn:
            assert False
            
async def main(loop):
    try:
        print("(before) Loop closed state: ", loop.is_closed())
        await postgres_stuff()
    except:
        print("(after) Loop closed state: ", loop.is_closed())
            
            
loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
```

And here's the output from running that script:

```
(env) C:\Dev> python test.py
(before) Loop closed state:  False
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    loop.run_until_complete(main(loop))
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\base_events.py", line 325, in run_until_complete
    self.run_forever()
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\base_events.py", line 295, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Python 3.5\lib\asyncio\base_events.py", line 1218, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Program Files (x86)\Python 3.5\lib\selectors.py", line 314, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Program Files (x86)\Python 3.5\lib\selectors.py", line 305, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
Future exception was never retrieved
future: <Future finished exception=OperationalError('could not connect to server: Connection refused (0x0000274D/10061)\n\tIs the server running on host "lo
calhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused (0x0000274D/10061)\n\tIs the server runnin
g on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n',)>
Traceback (most recent call last):
  File "C:\Dev\py\glotpod\glotpod-ident\env\lib\site-packages\aiopg\connection.py", line 118, in _ready
    state = self._conn.poll()
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

(after) Loop closed state:  True
Unclosed connection
connection: <aiopg.connection.Connection object at 0x0338EFF0>
```

**Comment by mpaolini** [comment]
with the proposed patch in #124 the output is now

```
(before) Loop closed state:  False
(after) Loop closed state:  False
```
