### ISSUE TITLE
create_all issue

### ISSUE THREAD

**Issue by philsong** [aio-libs/aiopg#244]
Traceback (most recent call last):
  File "bootstrap_data.py", line 39, in <module>
    loop.run_until_complete(main())
  File "/Users/phil/.pyenv/versions/3.5.2/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/Users/phil/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Users/phil/.pyenv/versions/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "bootstrap_data.py", line 20, in main
    await db.create_schemas(db.engine)
  File "/Users/phil/work/messenger/server/messenger/database.py", line 266, in create_schemas
    await metadata.create_all(engine)
  File "/Users/phil/.pyenv/versions/bixin352/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 3823, in create_all
    bind._run_visitor(ddl.SchemaGenerator,
AttributeError: 'Engine' object has no attribute '_run_visitor'

**Comment by asvetlov** [comment]
`metadata.create_all()` is not supported.

**Comment by philsong** [comment]
is it easy to support it? by now, it is too comlex, define model in ORM but  create table using sql statement.

**Comment by asvetlov** [comment]
It's impossible.
Technically you might use `CreateTable` DDL like this: https://github.com/aio-libs/aiopg/blob/master/tests/test_sa_connection.py#L409

But I strongly recommend to start using alembic tool: you need migrations anyway.
