### ISSUE TITLE
Error when canceling during transaction begin.

### ISSUE THREAD

**Issue by orez-** [aio-libs/aiopg#332]
I'm seeing an issue when my coroutine is cancelled while trying to begin a transaction:
```python
async with self.db.replica.acquire() as conn, conn.begin():
    res = await conn.execute(query)
    return await res.scalar()
```
```python
Traceback (most recent call last):
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 235, in get_current_version
    async with self.db.replica.acquire() as conn, conn.begin():
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/utils.py", line 77, in __aenter__
    self._obj = yield from self._coro
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/sa/connection.py", line 171, in _begin
    yield from self._begin_impl()
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/sa/connection.py", line 180, in _begin_impl
    yield from cur.execute('BEGIN')
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/cursor.py", line 113, in execute
    yield from self._conn._poll(waiter, timeout)
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/connection.py", line 240, in _poll
    raise exc
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/connection.py", line 237, in _poll
    yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
  File "/opt/python3.6/lib/python3.6/asyncio/tasks.py", line 345, in wait_for
    yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 354, in middleware
    return await handler(request)
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 385, in middleware
    response = await handler(request)
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/authentication/__init__.py", line 42, in middleware
    return await handler(request)
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/health.py", line 37, in health_check
    'data_version': await request.app.get_current_version(),
  File "/home/project/.pex/install/project-0+unknown-py3-none-any.whl.fd4fcf00c6491ee26d0a46ece96c5eca887e87a0/project-0+unknown-py3-none-any.whl/project/core/app.py", line 237, in get_current_version
    return await res.scalar()
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/utils.py", line 140, in __aexit__
    yield from self._pool.release(self._conn)
  File "/home/project/.pex/install/aiopg-0.13.0-py3-none-any.whl.2df26f3f2b931863ced66bc4d8059fd21bba4006/aiopg-0.13.0-py3-none-any.whl/aiopg/sa/engine.py", line 169, in release
    raise InvalidRequestError("Cannot release a connection with "
aiopg.sa.exc.InvalidRequestError: Cannot release a connection with not finished transaction 
```

It seems like the issue occurs when the [cursor coroutine](https://github.com/aio-libs/aiopg/blob/ba3a3424680215be28033b03c180a0683028dbf9/aiopg/sa/connection.py#L178) is interrupted. This is after [the `_transaction` is set on the SA connection](https://github.com/aio-libs/aiopg/blob/ba3a3424680215be28033b03c180a0683028dbf9/aiopg/sa/connection.py#L170), but since the error is in the `_TransactionContextManager`'s `__aenter__`, its `__aexit__` is never called to issue a rollback (oddly the `__aexit__` seems to be called successfully if the error is in the `try: finally:` block below this. I don't understand how this happens). Since we have a transaction, and it's not "finished" (although technically it was never started), the engine doesn't realize it can release the connection.

**Comment by apporc** [comment]
+1 for this bug.

**Comment by asgoel** [comment]
Any updates on this? We are seeing this too.

**Comment by achimnol** [comment]
+1 for me.

**Comment by achimnol** [comment]
For short-lived HTTP requests, we could live with `aiojobs.atomic` which prevents cancellation-in-the-middle of transactions.
The problem is that we are using WebSockets for streaming sessions, where I cannot rely on `aiojobs`.

**Comment by vir-mir** [comment]
Can you write a test so that we can reproduce the behavior? aiopg in only one case raises this `CancelledError` exception when postgresql interrupted the connection itself.
