### ISSUE TITLE
aiopg.sa don't work

### ISSUE THREAD

**Issue by Bernard04** [aio-libs/aiopg#409]
```
Original exception was:
Traceback (most recent call last):
  File "/projects/api/PgSQL.py", line 2, in <module>
    from aiopg.sa import create_engine
  File "/usr/local/lib/python3.6/dist-packages/aiopg/sa/__init__.py", line 2, in <module>
    from .connection import SAConnection
  File "/usr/local/lib/python3.6/dist-packages/aiopg/sa/connection.py", line 3, in <module>
    from sqlalchemy.sql import ClauseElement
ModuleNotFoundError: No module named 'sqlalchemy.sql'; 'sqlalchemy' is not a package
```

But i did already install sqlalchemy and use in projects. Help me please.

**Comment by asvetlov** [comment]
I'm not a wizard.
The only suggestion is dropping `sqlalchemy.py` from your local folder.
Anyway it is not `aiopg` problem but some weirdness in your code.
