### ISSUE TITLE
SystemError exception with psycopg2 2.8

### ISSUE THREAD

**Issue by TTRh** [aio-libs/aiopg#556]
Using `aiopg[sa]` it pull the latest release from `psycopg2-binary-2.8` (2 days ago) and i got this exception with `postgres:9.6.1` : 

```
Exception in callback Connection._ready(<weakref at 0...x7f0d9caa1a20>) at /usr/local/lib/python3.7/dist-packages/aiopg/connection.py:132
handle: <Handle Connection._ready(<weakref at 0...x7f0d9caa1a20>) at /usr/local/lib/python3.7/dist-packages/aiopg/connection.py:132>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/aiopg/connection.py", line 141, in _ready
    state = self._conn.poll()
SystemError: unexpectedly, there's no async cursor here
```

**Comment by TTRh** [comment]
Seems to be fixed by : https://github.com/psycopg/psycopg2/issues/887
