### ISSUE TITLE
Migrate from "yield from" to await (TypeError: object Engine can't be used in 'await' expression)

### ISSUE THREAD

**Issue by vvv-v13** [aio-libs/aiopg#71]
Hi, i replaced in my code "yield from"  to "await", and received Traceback:
"TypeError: object Engine can't be used in 'await' expression"

```python
async def db_psql_middleware(app, handler):
    async def middleware(request):
        db = app.get('db_psql')
        if not db:
            app['db_psql'] = db = await create_engine(app['psql_dsn'], minsize=1, maxsize=5)
        request.app['db_psql'] = db
        return (await handler(request))
    return middleware


async def psql_select(request):
    with (await request.app['db_psql']) as conn:
        result = await conn.execute(models.select())
```

Traceback
```python
[2015-09-17 14:50:29 +0300] [26045] [ERROR] Error handling request
Traceback (most recent call last):
  File "/Users/vvv/src/backend-tools/python/asyncio/venv35/lib/python3.5/site-packages/aiohttp/server.py", line 272, in start
    yield from self.handle_request(message, payload)
  File "/Users/vvv/src/backend-tools/python/asyncio/venv35/lib/python3.5/site-packages/aiohttp/web.py", line 85, in handle_request
    resp = yield from handler(request)
  File "/Users/vvv/src/backend-tools/python/asyncio/app.py", line 39, in middleware
    return (await handler(request))
  File "/Users/vvv/src/backend-tools/python/asyncio/app.py", line 46, in psql_select
    with (await request.app['db_psql']) as conn:
TypeError: object Engine can't be used in 'await' expression
```

**Comment by asvetlov** [comment]
Thanks for report.

**Comment by jettify** [comment]
As far as I can tell ``Engine`` class should have proper ``__await__`` magic method in order use idiom ``with await pool as conn``. Any way full set of python 3.5 features have not been merged, but you can play with https://github.com/aio-libs/aiopg/tree/await branch

**Comment by avanov** [comment]
Any chance to see it merged soon?

**Comment by asvetlov** [comment]
Will wok on it next weeks

**Comment by playpauseandstop** [comment]
Maybe to better implement proper `async with ...` instead of `with (await ...) as ...`?

For my projects I'm using next async context manager,

```python
class ConnectionContextManager(object):

    def __init__(self, engine):
        self.conn = None
        self.engine = engine

    async def __aenter__(self):
        self.conn = await self.engine.acquire()
        return self.conn

    async def __aexit__(self, exc_type, exc, tb):
        try:
            self.engine.release(self.conn)
        finally:
            self.conn = None
            self.engine = None
```

but it can be rewritten to,

```python
class ConnectionContextManager(object):

    def __init__(self, engine):
        self.conn = None
        self.engine = engine

    def __aenter__(self):
        self.conn = yield from self.engine.acquire()
        return self.conn

    def __aexit__(self, exc_type, exc, tb):
        try:
            self.engine.release(self.conn)
        finally:
            self.conn = None
            self.engine = None
```

to support both Python 3.4 and 3.5 codebases, I believe.

**Comment by asvetlov** [comment]
It's backward compatibility issue.
If we support `with (yield from pool) as conn:` then we should support `with await pool as conn:` also.

**Comment by samuelcolvin** [comment]
+1 for this, it would make using aiopg with `3.5` far cleaner.

**Comment by shongololo** [comment]
another +1

**Comment by samgre** [comment]
+1 from here too

**Comment by asvetlov** [comment]
Working on it

**Comment by farin** [comment]
+1

**Comment by asvetlov** [comment]
aiopg core has been ported since 0.8.0
aiopg.sa still uses old style.
Any volunteers?

**Comment by jettify** [comment]
If there are no volunteers, I can do PR, I need to do similar thing for aiomysql anyway.

**Comment by jettify** [comment]
Created PR https://github.com/aio-libs/aiopg/pull/90

**Comment by asvetlov** [comment]
Fixed by #90

**Comment by kakovskyi** [comment]
Awesome, thanks.

**Comment by PvsManiyan** [comment]
Hi 
I got this error while running the nginx server .with async await 
object _SessionRequestContextManager can't be used in 'await' expression
